### ISSUE TITLE
array_position  does not exist

### ISSUE THREAD

**Issue by xyun52** [dotnetcore/EntityFrameworkCore.GaussDB#3]
字符串数组过滤报错
linq : .Where(t => arr.Contains(t.Name))

sql : WHERE array_position(@__arr_0, NULL) IS NOT NULL))

fail: Microsoft.EntityFrameworkCore.Query[10100]
      An exception occurred while iterating over the results of a query for context type 'Server.Data.AppDb'.
      GaussDB.PostgresException (0x80004005): 42883: function array_position(text[], unknown) does not exist
```[tasklist]
### Tasks
- [ ] https://github.com/dotnetcore/EntityFrameworkCore.GaussDB/issues/3
```

**Comment by wangpengxpy** [comment]
哪个版本？6.x or 8.0？

**Comment by xyun52** [comment]
openGauss 5.0
Efcore 8

**Comment by wangpengxpy** [comment]
有环境没，我手头没有环境了，没法做验证测试

**Comment by wangpengxpy** [comment]
经确认，高斯基于pg9.2低版本，函数【array_position】不存在，最近将会修复此问题

**Comment by wangpengxpy** [comment]
该问题已修复，请更新至8.0.1版本哈再验证看看，确认ok后我再关闭issue @xyun52
